#!/bin/bash
source ./../set-env	

curdir=$(pwd)

cd files;
# upload files from the cur directory to the destination bucket,
# also, making it public files.
aws s3 sync . s3://$WWW_BUCKET --region $WWW_REGION --acl public-read 
cd $curdir
